# Generated by Django 5.2.7 on 2026-03-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mooddetection',
            name='mood',
            field=models.CharField(blank=True, choices=[('happy', 'Happy'), ('neutral', 'Neutral'), ('sad', 'Sad'), ('surprise', 'Surprise'), ('angry', 'Angry')], max_length=10, null=True),
        ),
    ]
