# Generated by Django 5.2.7 on 2026-04-13 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0004_alter_mooddetection_mood'),
        ('posts', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mooddetection',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
    ]
