# Generated by Django 5.2.7 on 2026-03-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='spotify', to='spotify.track'),
        ),
    ]
