# Generated by Django 5.2.7 on 2026-03-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='genre',
            new_name='mood',
        ),
        migrations.AddField(
            model_name='track',
            name='embed_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
