# Generated by Django 5.2.7 on 2026-03-13 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spotify', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listeninghistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listeninghistory',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.track'),
        ),
        migrations.AddField(
            model_name='trackfavorite',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.track'),
        ),
        migrations.AddField(
            model_name='trackfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='listeninghistory',
            constraint=models.UniqueConstraint(fields=('user', 'track'), name='unique_user_track_history'),
        ),
        migrations.AddConstraint(
            model_name='trackfavorite',
            constraint=models.UniqueConstraint(fields=('user', 'track'), name='unique_user_track_favorite'),
        ),
    ]
