# Generated by Django 5.2.7 on 2026-03-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='spotify_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
