# Generated by Django 5.2.7 on 2026-03-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_profile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_url',
            field=models.TextField(blank=True, default='uploads/defaultProfile.jpg', null=True),
        ),
    ]
