# Generated by Django 5.2.7 on 2026-04-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_profile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_url',
            field=models.ImageField(blank=True, default='uploads/defaultProfile.jpg', null=True, upload_to='uploads/'),
        ),
    ]
